
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-08-27T11:25:29+1000",
 "dirty": false,
 "error": null,
 "full-revisionid": "0fd643d27267c5627f34a38b709b0bb7022d2c80",
 "version": "1.1.7+12.g0fd643d"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
